language: python
sudo: false
env:
  global:
    - BUILD_DOCS: false
    -   secure: "fz2qITfux6fVyqhX6k8L7w6kPrxaMOCuIriGS1aBg4pAyi0bdU8XkP/KUevq9Ep5/nbf2FCSd4cgdPEYAVC97NuRpHjux6kjWlMGYVnjzA3F8GqMAWmay00uz3zOXXxEqURekOXANjGOXVOzfZUW61OWadGt/y5ThRmRb2l/CH/4viQ9GaDrdwa/0BTQrEyxvW3R1SdI9vcczf42XDmcHeJdnQfSJCS1pjIdtbTpXvk45voOuUBsZRzhMEL2+mg6U6CAi8xk+VnncWOxW+jMF316Gl5uG9nLHmZmMC0pL2OoWtgvFlTheca3LOPLAk/1m4+TYfQ4/iEgup0uzGd2JhwZ6XjxC4dzQfomSaizep97Fjp+zb0gIGvSIQXvA5xHgvbsf6qBKLJ1z8w689XaQlfUx1Lmrrxmgj/mEggMvYnvpzPmgLfkedXVgy+n3km9qsUQ/4E1sAWYWz5Z4Xssyyp+mQX5jAdrpcOOKIYVh7Vpn5UtA7K94g1CMVIoygPkE67+Y3B+NcMXaiN19k6o1Sxe1mgsIkiz8+174u3a3bGarxkAgT+niasCy4i9lI3sZ5IvGiYc84j8i2SjUbrNNWcVbDMFR9GRnixpVJxu1lTP0MJnnK5pIp6PUtFGyNgtDPKRRGjnJAFvXZ40CTfR+c4F0MoXpJ2i1SPnRQhVFZ4="
matrix:
  include:
    - BUILD_DOCS: true
      python: 3.5
      GH_REF: github.com/ericdill/ericdill.github.io
      BUILD_DOCS_BRANCH: 'build-docs'
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

python:
  - 3.4
  - 3.5

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  # clone conda install/build/upload helper scripts and make them executable
  - git clone https://github.com/NSLS-II/nsls2-ci ~/scripts
  - pushd ~/scripts
  - chmod +x *.sh
  - . install-miniconda.sh
  - . init-metadatastore.sh
  - . init-filestore.sh
  - popd

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv nose python=$TRAVIS_PYTHON_VERSION scipy requests matplotlib jsonschema traitlets pytest coverage
  - source activate testenv
  - conda install metadatastore databroker ophyd historydict boltons doct toolz tifffile pymongo pcaspy pyepics readline super_state_machine cycler xray-vision lmfit jinja2 -c soft-matter
  - conda remove metadatastore databroker filestore --yes --force
  - pip install codecov
  - python setup.py install
  # Need to clean the python build directory (and other cruft) or pytest is
  # going to find the build directory and get confused why there are two sets
  # of every test file
  - git clean -xfd
  - python -c "from filestore import utils, conf; utils.install_sentinels(conf.connection_config, 1)"

script:
  - if [[ BUILD_DOCS == 'true' ]]; then
        . ~/scripts/do-the-docs.sh;
    else
        coverage run run_tests.py;
        coverage report -m;
    fi;

after_success:
  - codecov
